### ISSUE TITLE
User-Styles/User-Scripts

### ISSUE THREAD

**Issue by lasar** [matigo/nice_social#10]
Hello there.

I am wondering whether it would be useful to provide a mechanism for users (like me) to add in an additional CSS file (or perhaps even JS file, but that brings its own set of questions) that will be loaded in addition to the standard styles.

I have made small modifications to `css/style.css` that I would like in my copy of nice_social, but which don't belong in the "real" source code. I'm wondering how to handle that.

Or perhaps another idea: IF desired, a user could create a user directory:

    user/
        config.js
        style.css
        script.js
        [any other assets]

This directory could even be its own git repo, separate from the core code. That way customizations could be done without ever touching the main codebase.

**Comment by mttmccb** [comment]
Are you thinking of user defined themes? or making them more widely available?

**Comment by lasar** [comment]
For now, just a fiddling playground. For instance I don't like the background images behind the three streams, so I made a small modification to make them smaller and put them in a corner.

An option to have multiple themes (light mode, dark mode, high contrast, etc) in the app would also be interesting, but a different feature I think.

**Comment by lasar** [comment]
I guess there's a bigger question that would influence all these questions: What does nice_social want to be?

- The codebase for the site nice.social made public so others can improve on that site
- A basis for setting up your own ADN client

Yes, it's now both. But is the second point really something we should work towards (for instance by making it easier to customize each copy)? How many people are seriously going to keep a copy running, apart from development setups?

Just questions, with no answer from me :)

**Comment by matigo** [comment]
Making the site super customizable would be interesting, and I like the idea of giving people more control over elements. An upcoming release to the main Nice software will include a rather robust settings screen that will begin to replace the slide-out menu functions. It would be possible to manually specify resources/preferences in there, too.

The question really comes down to effort and free time.

As for "what does nice_social want to be", the answer is a little simplistic: it's an example.

The code is being made available for people to use if they wish, to customize or enhance if they wish, and to fork into a competitor if they wish. It's an example of the ideals that I believe in, and an example for people who are concerned about the future viability of the network.

That's really a topic for a blog post, though … :P

**Comment by lasar** [comment]
Thanks for your input. As for my initial question, I was thinking of making the following additions to the config.js file:

- `niceConfig.addStyles = […]` -> optional paths to additinal CSS files that will be loaded
- `niceConfig.addScripts = […]` -> optional paths to additinal JS files that will be loaded
- `niceConfig.windowTitle = 'Nice.Social'` -> Text for title tag and header

And that's it really. That would scratch my immediate itch and is simple enough.

If I were to implement these features and send a PR, would you include this in the code?

**Comment by lasar** [comment]
This, of course, would only make the thing dev-customizable, NOT user-customizable.

Apart from switchable themes it might also be fun to add a text field for custom CSS rules. But I'll wait out your plans for the sidebar replacement before going in that direction more.

**Comment by mttmccb** [comment]
Sounds like a good plan, I didn't really consider the 2nd option but if it's easy to enable and opens up user customization then why not?

**Comment by matigo** [comment]
I've taken the liberty to add `sitename` to the config.sample.js file. This will allow people to set the name of the site to anything they'd like instead of Nice.Social. This change is found in the 15E081 Release.

**Comment by matigo** [comment]
Looking over this, I believe that the time has come to close the ticket. A lot of the customisations are either covered in other tickets or solved.
