### ISSUE TITLE
Slowness on iPad

### ISSUE THREAD

**Issue by lasar** [matigo/nice_social#11]
I've recently been experiencing slowness on the iPad again, when "Show Live Timestamps" is active. After deactivating it everything is fine again. If I remember correctly you made modifications here (after which it just said "less than one minute" etc) that improved things, but perhaps there is a regression somewhere.

Not a priority bug for me right now, just an observation.

**Comment by matigo** [comment]
Very odd. Does this slowdown also exist on the nice.social website? I don't think the redrawList() function has been updated recently.

**Comment by lasar** [comment]
Yes, I'm still using nice.social (not my clone) on the iPad. It's all fine on the desktop, as usual.
I can't tell since when the issue might exist, since I don't usually interact much on the iPad. But (now) when I tap a post to reveal its icons so I can look at the thread, it takes forever.

**Comment by matigo** [comment]
Very odd. I'm using the site on an iPad right now. Can you tell me what kind of iPad you have? I may need to do something for certain situations.

**Comment by lasar** [comment]
It's a 3rd gen iPad.

**Comment by matigo** [comment]
Closest thing I have to test with is a 4th Gen iPod Touch. Will check to see what's going on. Thanks for letting me know :)

**Comment by mttmccb** [comment]
Sadly I have no iPad available to test it on, an iPad Mini (1st Gen) would have been a good one too.

**Comment by matigo** [comment]
I've just rolled out a number of updates that may resolve the slowness issue, including a solution to Issue #18, which I believe may have had something to do with the problem. The columns were being checked far too regularly in a silly fashion, so that's been updated. Now it's also possible to set a maximum number of posts per column, which should go a long way to limiting DOM checks.

Let me know if the problem persists.

**Comment by matigo** [comment]
Some work has been put into resource optimisation (CPU and Memory, mostly). Hopefully this will help the iPad breathe a little better.

(Update is *not* on Nice.Social at this point)

**Comment by matigo** [comment]
This should be handled with a lot of the updates that have come out recently.
