### ISSUE TITLE
Interaction Bar Not Closing on Reply

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#12]
The interaction bar (the list of icons in each post that is hidden by default) is not disappearing after responding to a post. This needs to be corrected.

**Comment by mttmccb** [comment]
Hmm, I can't find any code that selects it, still working my way through how it all works.

**Comment by mttmccb** [comment]
@matigo the offending line is (this one)[https://github.com/matigo/nice_social/blob/master/js/core.js#L1459] it's looking for something that doesn't exist as far as I can tell.

**Comment by mttmccb** [comment]
Sorry that's not it... found it now.

**Comment by mttmccb** [comment]
haha so it seems there a lot of ways to reference an issue :P

**Comment by mttmccb** [comment]
I also understand a little more after I found [TL], you might be better mirroring what [ES6 uses](http://updates.html5rocks.com/2015/01/ES6-Template-Strings) so when it comes around you don't have to make many changes. Some might even exist in [ES5](https://github.com/addyosmani/es6-equivalents-in-es5#template-literals)

**Comment by matigo** [comment]
I plan on re-writing how posts are created this weekend, time permitting. The ES6 formatting might just work a little better for what's happening here, too. Thanks for letting me know about this, as I hadn't seen it before.
