### ISSUE TITLE
Drafted Messages Lose reply_to ID

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#122]
As the title says, when a person gets a draft message reloaded into the post box, it does not include the `reply_to` ID.

**Comment by mttmccb** [comment]
I'm not doing drafts yet but storing little things like this is getting to be frustrating, I want to avoid localStorage

**Comment by matigo** [comment]
In my case `localStorage` is the best way to keep the information in the browser without potentially breaching a person's privacy. I don't want to have this information on any of my servers, and it doesn't make sense to store this in a private channel owned by the account as, if the network connection disappears, people will not be able to save their draft.

It's not a perfect solution, but it does skirt the privacy issues that I am working hard towards enforcing :)

**Comment by mttmccb** [comment]
yep, I rather use a private channel if available... localStorage is probably the best option in that case.

**Comment by matigo** [comment]
Do let me know if you work out a pseudo method that will check for network connectivity and write to a channel or `localStorage` depending on best case. I'd integrate the channel into Nice :P

**Comment by matigo** [comment]
This seems to have been caused by the `saveDraft()` function missing a semi-colon. I've resolved the issue and also restored the draft to being something that is kept between sessions in the event a person doesn't have a network connection when they save the draft.

Closing issue.
