### ISSUE TITLE
IE11+ support

### ISSUE THREAD

**Issue by 0xMF** [matigo/nice_social#15]
I tried to run as instructed in the README but IE wasn't connecting to ADN to authenticate. The click event is firing doAction() but after that nothing happens. Could it be that the jquery version required by underscore (jquery-1.9.1.js) was not found. I tried after I included the jquery-1.9.1.js location within the script tag in index.html but that did not help either. 

Any help on how to get over this initial stage would be very welcome.

**Comment by matigo** [comment]
Interesting. `jquery.min.js` is 1.9.1. Is `underscore-min.js` specifically requesting a file by that name?

**Comment by 0xMF** [comment]
doAction() calls another function which requests for underscore-min, which in turn looks for jquery.min  (jquery.min is within the first few lines of underscore-min). I hope I got that sequence correct. I could only see (in the developer tools for IE) the click event firing the call for doAction() after that there is nothing.

**Comment by 0xMF** [comment]
If it's of any consolation, Chrome on Windows does the same thing... i.e. does not authenticate....does nothing when 'Sign In' is clicked.

**Comment by matigo** [comment]
It's not much consolation as I'm having trouble duplicating the issue. Will try with a fresh VM tomorrow, though. Thanks for the update :)

**Comment by matigo** [comment]
I do believe this is mostly resolved. I've done a bunch of testing, and WinX seems to like the newer versions of Nice. Closing ticket.
