### ISSUE TITLE
post submission should not be possible before attached image is uploaded and linked

### ISSUE THREAD

**Issue by snrkl** [matigo/nice_social#177]
Steps to reproduce:
1) Create a new post;
2) Type some text;
3) Decide to add an image attachment, so you click the (+) button and choose "Upload File"
4) Select your file;
5) Click Open
6) Send your message before the file details are added to your message.

What I expected to happen:
The post won't be sent until the upload action is finished and the attachment link is in my post.

What actually happened:
Post is sent without the attachment link

Additional Notes:
Additionally, trying to send a new message with the same attachment fails. I assume this is because the file is already uploaded to the web based file system and is possibly either errors out (untrapped) or is timing out. Attempts to send a new message with the previously botched attachment just hangs. Renaming the file will then allow you to attach it to a new message.

Chrome Version 44.0.2403.157 (64-bit) on OS X 10.10.3 (14D72i) 
nice.social version 0.9.9.9

**Comment by matigo** [comment]
This has been resolved and is part of Nice as we speak. Thanks for reporting the problem.
