### ISSUE TITLE
Avatar color change

### ISSUE THREAD

**Issue by blumenkraft** [matigo/nice_social#189]
Well, not that it's a bad color, but it is supposed to be yellow (completely).

<img width="35" alt="screenshot 2015-09-11 18 29 19" src="https://cloud.githubusercontent.com/assets/4653850/9820299/3e025d60-58b3-11e5-9bc1-a8248bef90a7.png">

**Comment by matigo** [comment]
I'm not seeing this anywhere. I've tried every theme, too. Could you let me know a bit more about how you saw this colour change?

**Comment by blumenkraft** [comment]
Sorry, not sure what triggered it. Only thing i can say is that since i turned off proxy it never occurred again. If i ever see it again i will update the thread.

**Comment by matigo** [comment]
Closing ticket. Will keep an eye out for this problem, though.
