### ISSUE TITLE
Bullet point lists with asterisks are wrongly rendered italics

### ISSUE THREAD

**Issue by hutattedonmyarm** [matigo/nice_social#191]
[Example post](https://alpha.app.net/bazbt3/post/64566283)

Looks like this: 

<img width="355" alt="screen shot 2015-09-13 at 10 40 32" src="https://cloud.githubusercontent.com/assets/664905/9835953/e8bcb510-5a03-11e5-964d-483edc213dbe.png">

Should look like [this](https://alpha.app.net/indigo/post/64566719)

**Comment by hutattedonmyarm** [comment]
Interestingly [this](https://alpha.app.net/tomcat/post/64566772) one works just fine

It might be because of new lines, looks like Kirby is using new line characters not supported in Nice

**Comment by matigo** [comment]
When is a line return not a line return? When it's a `&#13;`. This is a Windows-specific issue as the ADN API didn't change it into a `<br>` tag. As a result Nice (and any other client that would rely on the `post.html` value) would see it as a single line.

This will be resolved with 1.0.3.

**Comment by matigo** [comment]
Done and done, as you can see here:

![fixed](https://cloud.githubusercontent.com/assets/3123903/9836501/902f3c2a-5a57-11e5-9ef1-9e32bd801f70.png)

Closing ticket.
