### ISSUE TITLE
Show canonical URL for post

### ISSUE THREAD

**Issue by lasar** [matigo/nice_social#199]
When I want to reference a post somewhere else I want to use the canonical URL  (i.e. on like this: https://alpha.app.net/lasar/post/64839906). As far as I can tell I can't see this in the Nice frontend yet.

I'm not sure where this would be added. A while ago each post had a placeholder "..." icon that could be repurposed for an "Info" popup. Perhaps this popup can later be expanded to show all reposts/likes and things like that.

I'd be happy to work on this feature myself but am not sure when I will find the time.

**Comment by matigo** [comment]
Would this be a clickable link, or something that you can copy to the clipboard?

**Comment by lasar** [comment]
I'd make it a simple link with target="_blank" so it opens in a new window, or can be copied by right-clicking it.

**Comment by matigo** [comment]
Done. You'll see it appear in conversation view with the stacked lines. Click on that to reveal a sub-menu of stuff. It's a bit ugly right now, but we'll get it fixed up eventually :)
