### ISSUE TITLE
Unable to authorise

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#2]
I've walked through all the steps but I'm not able to authorize. I get 
![failed-to-open-page](https://cloud.githubusercontent.com/assets/7456613/7499731/75582228-f421-11e4-9e12-ec1c5effbe9a.png) in Safari, nothing happens in Chrome and 
![problem-loading-page](https://cloud.githubusercontent.com/assets/7456613/7499753/9de404e6-f421-11e4-9c08-a63f8acaef06.png) in Firefox.

I have a paid account. Any ideas?

**Comment by lasar** [comment]
Is your app online somewhere to try out?

**Comment by mttmccb** [comment]
No it was hosted statically from the file:///, not sure why it won't authorise.

I've setup apache following [these instructions](http://coolestguidesontheplanet.com/get-apache-mysql-php-phpmyadmin-working-osx-10-10-yosemite/) and updated the redirectURI and it works.

So either it won't work from file:/// or there's something I'm missing?

**Comment by matigo** [comment]
This seems to be a security feature within most browsers. A website cannot redirect a person to content hosted on their computer this way. I'll update the README file to reflect this.

Thanks for letting me know.
