### ISSUE TITLE
config.js in index.html not found (fixed with #20 but bug persists)

### ISSUE THREAD

**Issue by 0xMF** [matigo/nice_social#22]
While loading in Chrome (and IE) both report missing config.js. The link is there but there's no file with that name in the repo. I was able to find a simple, easy fix, and sent in a PR #20 but both Chrome and IE do not authenticate correctly. Chrome brings up the dialog box and tries to contact ADN, after that process I get this error message

Error

Please contact the website that sent you here and let them know that there is a problem with the Redirect URI.

IE11 does not bring up the dialog box to login, in fact IE11 just keeps spinning. Once I know Chrome works correctly I'll take a closer look at IE11 settings, but that shouldn't matter since IE11 works fine with nice when hosted at https://nice.social/

**Comment by mttmccb** [comment]
Did you put your key and redirect (and based on 15E081 site name too) into config.js? It's deliberately not in the repo, the idea you copy config.sample.js and rename it, add your secret keys and it's in .gitignore so it won't be committed.

Unless I'm misinterpreting your problem.

**Comment by matigo** [comment]
This appears to be a configuration issue. Issue #23 will include a more interactive solution for this problem.

Mark: do let me know if Matt and I are misunderstanding the issue. So long as a person creates the `config.js` file and puts it in the web root, the site should load properly, even with dummy data.
