### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#24]
How low are you going? Is there anything you've ruled out, for example pre IE8?

**Comment by matigo** [comment]
As this is an open project, I don't see why there would be any limit whatsoever. If a person wants to use IE 4.0 on a Windows CE handheld, then they can help the community if they have the means.

**Comment by mttmccb** [comment]
It was more from the perspective of feature X is only available in a certain age of browser/device so the options are:

- Find another way (potential similar to a shim probably more complex and wider support)
- Shim it (usually larger footprint and more likely to have limited support too but less complex)

I do like graceful degradation if possible.

**Comment by matigo** [comment]
Asking a handful of people to keep half a dozen or more VMs available to test the project in various retired browsers and OSes is not unrealistic, but not a wonderful use to time for a maximum of 1,000 people. Would it be worth the time and effort?

As of this post, 138 people have signed in to Nice.Social. Not sure how many people have downloaded the source to use it, but I doubt it's more than a dozen at this point.

Perhaps the best way to go forward with compatibility is to stay away from certain JavaScript libraries that are known to require the latest and greatest browsers, while sticking with plain JavaScript wherever possible. I like the work you've done to reduce the site's dependence on jQuery and, if it's at all possible, perhaps we can remove it completely or use something that is better for the purposes of the project.

Getting back to the main question, I guess I would say I'd like to see the following:

* IE8 and above (Desktop and Mobile)
* Opera 20+
* Firefox 20+
* Chrome 20+
Safari 7+

If other browsers are able to use the site, then I'll consider it a bonus.

Hope this answers your question :P

**Comment by mttmccb** [comment]
It does, there are options out there so I know what to rule out and where to focus.

It's becoming the norm to support evergreen browsers and not much else and as time passes I can see them being even more common.

It would be nice to have a SPA that doesn't rely on the latest and greatest and still works in older browsers.

**Comment by matigo** [comment]
Some work was done to ensure the core.js functions will work in IE7, particularly the post expiration elements.

**Comment by matigo** [comment]
IE versions prior to 9 will not be supported going forward. I'm seriously considering dropping Firefox, too. Closing ticket for now. Browser-specific problems will need their own number.
