### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#26]
One of the first things I tried to improve and failed was the way storage was handled, a few observations:

- For every save, read or delete it run ``hasStorage`` *every* time you save something even though it's probably something that could be checked once (probably minor...)
- You could bind the changing of the fields to update storage like [Mozilla's Web Storage Demo](https://github.com/mdn/web-storage-demo)
- Are you using the ``store`` for those that don't support localStorage and for other purposes?
- If storing multiple values it worth stringifying the JSON object?
- Potentially use [jStorage](https://github.com/andris9/jStorage), the PubSub side of it sounds interesting. Disclaimer: I've never used it but the support back to IE7 caught my eye.

I haven't done anything with it yet and if using ADN (files?) to store these settings it might not be worth the effort.

**Comment by matigo** [comment]
Let's see ...

The `hasStorage()` check looks at `window.localStorage` to see if it exists, so storing some sort of value would be just as fast as asking the browser again, I think. At this point it's not something I'm very worried about.

An earlier version of Nice did make use of a similar idea to Mozilla's Web Storage, but it had some problems with IE so I stopped and went back to something a little simpler. Perhaps  was doing it wrong, though.

Yes, `window.store` is used for non-persistent storage on all browsers. Browsers that do not support `localStorage` will also use `window.store` for all its information as well. Unfortunately, this means refreshing the site will lose all a person's information, including preferences.

I considered stringifying JSON objects, but am not sure if the constant string/unstring processing time would be worth the hassle. It's something I'd like to investigate at some point, though.

jStorage looks to have been replaced with something that looks very similar to what Nice is already doing, albeit in a more sophisticated manner. I wonder if there would be noticeable gains by going this route ...

Thanks for the thoughts, though. At this point I am not sure if storage needs to be replaced with something else. that said, I would be happy to entertain the idea if a strong enough case is made :)

**Comment by mttmccb** [comment]
I guess I always saw cookies as the natural fall back for localStorage, which improves the experience for older browsers somewhat. I suspect that's what jStorage is using to get the wider support. The new version doesn't support IE7 and Firefox 3 which might be not be a deal breaker.

**Comment by matigo** [comment]
I've had issues with JavaScript writing (and editing) persistent cookies, so have avoided doing so. There are a few things that I would like to see remain persistent, such as the items that use readStorage/writeStorage, so I am certainly open to options :)

**Comment by mttmccb** [comment]
I might have look at them and the support side of it. I think if it were to be used then it would be worth adding a function somewhere to clear the cookies set, it's annoying having to do it for all sites.

**Comment by matigo** [comment]
This issue seems to have been resolved with a recent merge. Closing ticket.

Thanks again, Matt :)
