### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#27]
Just putting it here to explore the possibilities :)

**Comment by 0xMF** [comment]
Good point.

**Rationale**: TypeScript abstracts browser/JS issues and provides an easier way to handle JS.

**Pros**:  would make nice easier to port to older/newer versions of JS
**Cons**: adds another layer to maintain, plus issues that TS (might) bring along

**Reference**:

1. Andres Hjelsberg [The Future of TypeScript: ECMAScript 6, Async/Await and Richer Libraries](http://channel9.msdn.com/Events/Build/2015/3-644)
2.  TypeScript definitions of common JS libraries [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped)
3. [Getting Started with Aurelia and TypeScript](http://blog.durandal.io/2015/05/06/getting-started-with-aurelia-and-typescript/)

**Comment by mttmccb** [comment]
It's sad but I really like how GitHub can pickup on the references, I've done a quick example for the functions I wrote the other day.

In this example I think it makes things more explicit what types should be passed/returned and of course you get all the nice compiler warnings.

**Comment by mttmccb** [comment]
Here's an example of [Using TypeScript in Visual Studio Code](http://blogs.msdn.com/b/typescript/archive/2015/04/30/using-typescript-in-visual-studio-code.aspx), I could have done with that an hour ago :-o

**Comment by 0xMF** [comment]
Dang, there seems to be no way of starring individual Issues :-o

**Comment by matigo** [comment]
Hmm ... for the sake of simplicity, I think any version of Nice that uses TypeScript should be done as a separate fork. I'd like to keep the Nice.Social code as simple as possible and, while something may be simple to a group of programmers, it introduces barriers to new people who may want to try their hand at making a custom ADN app.

I do wonder how advantageous this would be, though, and whether there are tools that would allow Coda2 to make sense of TypeScript files ...

**Comment by mttmccb** [comment]
It seems that there isn't a plugin available for Coda2 right now, I suspect it's because it would open the need for other tooling.

The main benefit if it's kept functional would be type checking, which will in turn will reduce bugs and reduce development time.

But I believe you'd get a bigger benefit by making use of OO features. TypeScript makes it easy to do that because you ca use features that don't exist in current JavaScript but it can be targeted to a version that is widely supported.

I've been trying to go the OO route in JavaScript (potentially a bad idea) but the horrible syntax routes and setup required to go that direction is painful. TypeScript (and the tooling) make that much easier.

But it would definitely raise the barrier to entry.

**Comment by matigo** [comment]
As I've mentioned, raising the barrier is the last thing I want to do. It would be great to see someone with zero web development experience pick this up and maybe learn a thing or two. Having a lot of requirements beforehand might limit such adoption.

That said, I do encourage a full fork that uses TypeScript if that's something you'd like to do. Then we could compete to see who can fix my awful code fastest :P

**Comment by 0xMF** [comment]
BTW, there are other options to TypeScript out there, for example: CoffeeScript and Dart compile to JS as well and they may have their own set of appealing features, so when looking at the nice project, as a whole, an implied blessing of one compile-to-JavaScript option over others has the potential of opening a different can of worms ... err issues :smiling_imp:

**Comment by matigo** [comment]
I still see those options as barriers to entry. That said, you are more than welcome to fork the project and make it better than the default. Heck, I might just come back later and steal your code back :P

**Comment by 0xMF** [comment]
yep, was thinking of a scenario like that. Initially use nice to understand JS and then rewrite nice in TS to achieve a higher degree of abstraction...from there see how much better TS makes adding of future features and handling of bugs (at least I'm hoping IE11 and better will be supported by default with TS).

**Comment by matigo** [comment]
Hope so. I'm looking for a way to make Nice better on Windows Phone devices, which is really hard as I don't have a Windows Phone. I do have an older HP iPaq 211 which ran WinMo 6.5, but that device is a completely different beast from a Windows Phone phone ...

**Comment by mttmccb** [comment]
There's a good chance the IE bugs are CSS related rather than JavaScript, in my experience it's typically the former.

**Comment by matigo** [comment]
Closing this question ticket. We can revisit whether to use TypeScript or something else when the core Nice functions are worked out.
