### ISSUE TITLE
Windows Phone Issues

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#29]
Windows Phone seems to have a number of issues according to @pme, which pretty much makes the tool unusable on the platform.

**Alignment Issues** - As the screenshot shows, the post box does not align itself with relation to the keyboard. This is also seen on some of the 4:3 iOS devices.

![Windows Phone Screenshot](https://nice.social/gitpics/wp_ss_20150510_0001.png)

**Scrolling** - Jittery and inconsistent

**RespondBar** - Inconsistently appears

Here are the posts from @pme:

* Still horrible. Scrolling is slow & judders to a stop while the site refreshes. I can’t get any actions to show up when I tap the area around/on the timestamp. I did manage once (somehow) to get into conversation view but was wanting to reply.
* I’m about to try a new post but I don’t hold high hopes for it.
* Fail. {Screenshot} is what I see when I try a new post. Very occasionally the letters are shown but in most cases, nothing. And you can forget about getting any action or input to happen while it's refreshing.

**Comment by matigo** [comment]
Thinking through text dialog box issues, I believe the most logical solution would be to have it appear 50px from the top when viewed on screens with horizontal resolutions below a certain threshold. Desktop applications can show the dialog in the centre. Thinking about some tablets, perhaps 1200px wide ought to be the minimum threshold ...

**Comment by mttmccb** [comment]
Yep that make sense, just a tweak to the @media for smaller devices?

**Comment by matigo** [comment]
For the dialog boxes and messages, yes. I'll do some testing to make sure everything works in both portrait and landscape mode (which is more difficult in many cases).

**Comment by matigo** [comment]
This should be resolved with the more recent updates. Testing in VMs shows some jitter still exists at the start of the web app launch but, after everything is loaded, the UI is pretty smooth.

Closing Ticket.
