### ISSUE TITLE
jquery.min.map missing

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#3]
Just throws a 404, I can't find a copy of it as it's using 1.9.1 so may easier for @matigo to add it.

Is it that particular version due to dependencies?

**Comment by matigo** [comment]
404 be gone! Thanks for letting me know. I don't think I've seen errors related to this file before, but am glad to whisk them away from the people who do.

**Comment by mttmccb** [comment]
It's only on this version, nothing I could see on nice.social, glad it's sorted, cleans up the console a bit more
