### ISSUE TITLE
Keep Documentation With Codebase?

### ISSUE THREAD

**Issue by 0xMF** [matigo/nice_social#31]
I'd like to grok the nice source code and keep notes, mainly for myself, about the design of nice to help me understand the logic flow of different things. I think this might have value to others as well. Once I get up to speed on things, I might be able to help contribute JS source. 

Would there be interest in having a separate docs directory (to help developers understand and get up to speed)?

**Comment by matigo** [comment]
I've been thinking a Wiki on here would be a better place for docs mainly because we can use Markdown and have it properly marked up into easily-readable HTML on a website. Do you think that a /docs directory with a series of documents would be a better way to organise the work?

**Comment by 0xMF** [comment]
The only advantage to a docs directory, as part of the project, would be that stand-alone, on-vacation, off-Internet, people would at least have a way of understanding the project. I don't think GH wikis can be downloaded with the git clone (unless I'm unaware).

If this sounds like a good idea, I am comfortable with AsciiDoc (preferred as that is the one I use daily and has much more features and export options) or Markdown.

**Comment by matigo** [comment]
One cannot use ADN without an Internet connection, which is why I was thinking the Wiki would be a better solution. One advantage to the /docs directory would be the point-in-timeness of the documentation. There will (ideally) not be a big difference between the docs and the code. A wiki will keep on being updated as the code evolves ...

**Comment by mttmccb** [comment]
Does the Wiki get included with the source code as another folder? Or just live on GitHub?

**Comment by mttmccb** [comment]
According to [About GitHub Wikis](https://help.github.com/articles/about-github-wikis/) they're add to the repo so can be update offline and they're in their own Markup language (with includes Markdown)

**Comment by 0xMF** [comment]
@mttmccb Excellent, I did not know that...and if so I would favour wikis too...and probably to keep things simple just use the native (GFM, GitHub Flavoured Markdown).

**Comment by matigo** [comment]
[Let the docs begin](https://github.com/matigo/nice_social/wiki). Not seeing any files in the source repository, but maybe there's a setting I need to enable. Will check it out tomorrow. Need to get some sleep.

**Comment by matigo** [comment]
Oh, I see. It's [a separate repository](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/). This might be something I'll add to the `README.md` file, then. It'll give people the option to take the docs if they so choose to. That'll also make it easier for them to have their own Wiki if they do fork the project.

Some docs are better than no docs ...

**Comment by mttmccb** [comment]
You beat me to it :) I was just looking at that page, it makes sense to keep it separate as code and docs are not really the same thing although a readme is essential and could point to the Wiki

**Comment by matigo** [comment]
A reference to the Wiki has been added to the `README.md` file, so people who would like to learn more about the tool can go there for details. Hopefully the Wiki will be a "living" document rather than something that is half-written and forgotten about.

I'll do my best to make sure that doesn't happen.
