### ISSUE TITLE
Non-Global Timelines Persist on Logout

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#33]
When a person logs out the Home and Mentions timelines persist if they were visible.

**Comment by matigo** [comment]
The easiest way to run through this would be to run through the timelines and hiding anything that is not global.

**Comment by mttmccb** [comment]
Are they currently hidden at the moment or created at runtime? Just wondering if removing them from the DOM would be do-able or cause problems.

**Comment by matigo** [comment]
The timelines are created and destroyed on the fly. The solution will probably be something as simple as running through  `window.timelines` and ensuring that o my the `'global'` valueis set to true before redrawing the timelines.

**Comment by matigo** [comment]
This issue (and one other silly problem) has been resolved with the most recent update. Closing Ticket.
