### ISSUE TITLE
Inline script in index.html

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#41]
Any particular reason it's not in an external file? I'm assuming it's related to performance? Or habit? :wink:

**Comment by matigo** [comment]
It's for both. I try to keep external files limited to 5 (very old habit) and I find that browser caching is less of an issue when I write and test code on the main page before moving it off the landing page (testing performance). From what I have seen, there are no problems keeping a minimal set of JavaScript on the main page that points elsewhere, and do prefer the pattern.

**Comment by mttmccb** [comment]
Limiting the files is definitely a good idea, my main criticism with inline (anything really) is that it's hard to debug during the development, although I've found caching a frustration it is outweigh by easy debugging.

I think I'm still thinking in terms of when it comes to put it live bundling and minifying whatever I can which will improve performance. Source maps help to debug when using those files when it is live.

I'll leave it where it is.
