### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#45]
There seems to be more than a few people who would really like a dark theme. I don't particularly like dark themes and find them really hard on the eyes. That said, what would be the best colour scheme to go with if one were to be made?

Using Chrome, I did some quick colour switching and came up with the following yucky scheme:

![Nice Dark Theme](http://nice.social/gitpics/nice_dark_theme.png)

Using #000 may be *too* dark, and having #fff on top of #000 would get tiring, I think. Inverting the colours might be enough, but it's an awfully lazy way to attack the problem.

**Comment by jextxadore** [comment]
What about #1F1F1F and #B4B4B4?

**Comment by matigo** [comment]
Would the #b4b4b4 be used just for the text, or for text and links? Right now the links in the dark theme above are #00f, which is probably too harsh a blue.

Here is a quick image showing #b4b4b4 on #1f1f1f:

![Grey on Black][http://nice.social/gitpics/grey_on_black.png]

**Comment by jextxadore** [comment]
Not sure how good #4D94FF would look

**Comment by matigo** [comment]
Okay ... I sat down and hammered this out rather than sleep, so it might be a little ugly and buggy, but you can now make your own colour schemes.

![Six of One, Half-Dozen of Another](http://nice.social/gitpics/color_selection.png)

You can open the preferences panel with an F3 command. Note that this is where all preferences will soon exist, so there is a high probability this design will change in the near future.

Do let me know if there's anything missing ... like a "Reset to Default" setting.

**Comment by matigo** [comment]
Note to Self:
* panels need to make use of the proper colour scheme
* the settings HTML should be dynamically generated from a JSON store rather than done the stupid way it is

**Comment by jextxadore** [comment]
Nicely done.

I find the following make a decent dark theme:

333333
1f1f1f
fff
D1D1D1
b4b4b4
D1D1D1

The only thing that's missing in the theming is a way to change the colour of the circular border in the avatars in the Mentions column.

**Comment by matigo** [comment]
This is now fully rolled out with 15E222. Closing Ticket.
