### ISSUE TITLE
Dismiss Image Gallery on Escape

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#49]
Since a New Post can be cancelled with an [Esc], it only makes sense that the image gallery should also disappear when this button is hit.

Requested by @blumenkraft

**Comment by matigo** [comment]
This has been completed, and works quite well. Closing Issue.

**Comment by blumenkraft** [comment]
Since a New Post can be cancelled with an [Esc], it only makes sense that the **conversation view** should also disappear when this button is hit. :)

**Comment by matigo** [comment]
The most recent update will dismiss all popovers regardless of what they are on [Esc].
