### ISSUE TITLE
Add /me Action Type

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#56]
A number of people on ADN have IRC backgrounds, and the `/me` feature is something that a lot of people enjoy -- myself included. This functionality could be brought to ADN as an annotation within the post so that, clients that support such a feature will have a "proper" display of an action. Clients that do not support the feature will see just a standard post with the same text.

**Concept**
Text: `/me takes a sip of coffee ☕️`
Becomes: `@matigo takes a sip of coffee ☕️`

No avatar or other annotation information would be displayed with a `/me` action.

**Comment by keichan34** [comment]
:+1:

**Comment by matigo** [comment]
You know ... rather than make a special datatype, this could be done just by checking to see if a message is prefixed with `/me`. Why limit this to posts from Nice when it could be done by anybody?

**Comment by matigo** [comment]
This has now been rolled out. Any post prefixed with `/me`, regardless of source, will show in a mIRC-style with a double-circle icon prefix.
