### ISSUE TITLE
ChromeBook Column Width Being Misreported

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#59]
It appears that the ChromeBook's browser does not properly report the scroll bar width, which results in the last timeline being dropped off (due to CSS constraints). To resolve this without getting too crazy on a browser-by-browser basis, people should have the ability to set the scrollbar width manually in the preferences panel. The default would be to use the value reported by the browser but, when overridden, the hard-coded value would be used to determine column width.

**Comment by matigo** [comment]
Done and done. A new item exists in the Preferences Panel, and it's pretty damn slick. I'm happier than a duck in a pond with this one.

**Comment by akulbe** [comment]
Hmm... not so sure yet. I have the column width set to -35 even, and it still only shows 3 columns. 

I know you know this already, but I'm putting it here to actually _contribute_ something to the matter.
![screenshot 2015-05-25 at 19 34 48](https://cloud.githubusercontent.com/assets/123279/7804257/263d3dd8-0315-11e5-846d-d97c437e5e1f.png)
![screenshot 2015-05-25 at 19 34 32](https://cloud.githubusercontent.com/assets/123279/7804258/263e1974-0315-11e5-9f6c-66cf8c2b7588.png)

**Comment by matigo** [comment]
Could you try something for me? Set the adjustment levels to positive numbers. Negative numbers make the columns wider. Positive numbers make the columns narrower. I'm thinking you'll need a number somewhere around +4 ...

**Comment by akulbe** [comment]
I tried it with both +4 and +8. No dice.
![screenshot 2015-05-25 at 22 46 35](https://cloud.githubusercontent.com/assets/123279/7806013/873f1aaa-0330-11e5-857c-888624307510.png)

**Comment by matigo** [comment]
I just pushed out an update. Could you refresh your browser and let me know what the reported screen resolution is? I've done some testing with your screen and the super-high resolution may be confusing some of the code ...

![Debug Settings](https://cloud.githubusercontent.com/assets/3123903/7806132/e48a0a94-03b7-11e5-864f-60e4de7c90fb.png)

**Comment by matigo** [comment]
Looks like this has been resolved for the people who reported the problem. Yay!

Closing ticket ಠ_ಠ
