### ISSUE TITLE
PM column sometimes vanishes

### ISSUE THREAD

**Issue by lasar** [matigo/nice_social#67]
I see that the PM feature is in the works, very nice!

However I noticed that the 4th column will vanish depending on browser width. While manually resizing the window it vanishes every few pixels, so I am assuming a rounding error that makes the column a pixel too wide.

**Comment by matigo** [comment]
You can adjust the column widths in the Settings by choosing "Column Widths" and moving the numbers around. Negative numbers increase the column width while positive numbers decrease the column width.

![Settings Panel](https://cloud.githubusercontent.com/assets/3123903/7858332/79901fa0-0572-11e5-9be2-d835b07d8ceb.jpg)
![Column Width](https://cloud.githubusercontent.com/assets/3123903/7858333/79e0d5bc-0572-11e5-85b4-535ee274dd5c.jpg)

**Comment by lasar** [comment]
OK, that'll solve the problem for me for now. Thanks for letting me know.

I'd still classify this as a bug.

**Comment by matigo** [comment]
It's one of those bugs that will be difficult to suss out. One of the big problems I'm facing is consistency across browsers. Chrome on different platforms seems to respond differently to the same JavaScript.
