### ISSUE TITLE
cmd/ctrl-K does not permanently clear PMs

### ISSUE THREAD

**Issue by lasar** [matigo/nice_social#68]
cmd/ctrl-K will clear all columns for me, but the PM column will refill a second later every time.

It's not an issue for me but I thought I'd make a note anyway. It doesn't feel like expected behavior.

**Comment by matigo** [comment]
This is interesting. It'll be resolved with the upcoming changes to the PM data storage methods. Thanks for letting me know.

**Comment by matigo** [comment]
Done and done. This will be part of the next roll out.

That said, I really dislike the way channels are handled in Nice.
