### ISSUE TITLE
Image don't have a pointer when you hover

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#69]

**Comment by matigo** [comment]
Are you referring to the `alt` text, or the cursor?

**Comment by mttmccb** [comment]
Cursor, I'll give the thing a full refresh and see if it resolves all those issues

**Comment by mttmccb** [comment]
Nope, still no pointer, I think it should have one but that's just me :)

**Comment by matigo** [comment]
That's just you, but we can leave this open to make it a CSS modification. Moving issue from Question to Enhancement.

**Comment by matigo** [comment]
Resolved. Closing Issue.
