### ISSUE TITLE
400 error bad request

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#70]
![nicesocial-image-upload](https://cloud.githubusercontent.com/assets/7456613/7869615/caf37d70-057b-11e5-8d71-5cdf8e23ed2c.png)

It persists...

**Comment by matigo** [comment]
Hmm ... the 400 Error may occur if the image string is not being converted to a proper `oembed` object.

Silly question but, looking at this issue and #71, is your CSS and `core.js` up to date?

**Comment by mttmccb** [comment]
Doesn't seem to be, now working...
