### ISSUE TITLE
File (name) stays in post

### ISSUE THREAD

**Issue by mttmccb** [matigo/nice_social#71]
![nicesocial-file-sticks-around](https://cloud.githubusercontent.com/assets/7456613/7869642/fb04ffa2-057b-11e5-845c-218846035737.png)

**Comment by matigo** [comment]
This is very odd ... and ugly. You should not see "choose file" or the filename. What browser are you using? The textbox also is not styled properly ...

**Comment by mttmccb** [comment]
I also had to make the textbox bigger, that's safari (in a fluid app, I haven't checked safari)

**Comment by mttmccb** [comment]
Also solved by a refresh (sorry it was late, I should have tried that...)
