### ISSUE TITLE
Force CSS/JS Refresh in Client

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#72]
Is it possible to force a browser or bridging application like Fluid to refresh the CSS and JavaScript files?

**Comment by mttmccb** [comment]
When I last looked into it was possible, other than changing the name of resource, for css this is usually just a case of adding a query string like  ?version=1.10 and it will be picked up as a new file. I'm not sure if this applies to javascript.... I'm also having the same issue, but Azure caches it too, for longer :/

**Comment by matigo** [comment]
Query strings are what I used when Nice.Social had a PHP back-end that did some work before sending the HTML to the client. It's very easy to do with something in the middle. When the files are just static there is a little more trouble.

I should investigate to see if an `.htaccess` rule could do a quick inline replace with a unix timestamp of the file as its version number. It wouldn't be an ideal solution, but it would still allow for resources to be cached locally and updated only when changes are made ...

**Comment by matigo** [comment]
I'm one step closer to this with an interesting bit of JavaScript in the header. Because Nice is almost 100% powered by JavaScript, it's possible to load most of the CSS and JavaScript resources after the page is in the browser without a serious visual problem (so far). As a result, it's possible to programmatically append a version number to the CSS and JS resources that are loaded after the fact.

This is something that I will test a bit more before rolling out on the Nice.Social domain.

**Comment by matigo** [comment]
This is actually working in the pre-release, and does not seem to affect performance in the least. For this reason, it'll be rolled out later this week for broader implementation.

Closing ticket.
