### ISSUE TITLE
Optional Show/Hide Column Headers

### ISSUE THREAD

**Issue by matigo** [matigo/nice_social#78]
Some people are not a fan of the background images and would rather see column headers.

**Comment by keichan34** [comment]
:+1:

**Comment by matigo** [comment]
Seriously? Why does everybody hate my background icons? =_=

**Comment by keichan34** [comment]
I don't know about anyone else, but I find that they're distracting and make the text harder to read.

**Comment by matigo** [comment]
That's the same thing other people have said, yes. For *my* eyes, though, it's perfect. :P

**Comment by matigo** [comment]
Done. People are able to show column names and hide the background graphics if they so choose. The column headers are currently available in English, German, and 日本語. I should ask a native Japanese speaker to confirm my horrible translations, as they're all in Katakana ...

Closing ticket either way.
